# Site settings
title: ggi88
description: > # this means to ignore newlines until "baseurl:"
    Blog ggi88
url: "http://ggi88.github.io"
baseurl: ""
logo: <b>ggi88</b>
paginate: 5
paginate_path: "/page:num/"
owner:
    email: 
        
    facebook:
        show: false
        name: "Ichihara Rifa"
        url: "https://fb.me/yuneharuka"
    github:
        show: true
        username: "ggi88/ggi88.github.io"
    twitter:
        show: false
        username: ""
    disqus:
        show: true
        username: "ggi88"
    linkedin:
        show: false
        profile: "https://linkedin.com/in/your-profile-id-here"
sass:
    sass_dir: _sass
    style: compressed
permalink: "/article/:title"
markdown: kramdown
highlighter: rouge
plugins:
    - jekyll-feed

google_analytics:
    ua: UA-116608951-1 
